export interface Task {
  id?: number; // Unique identifier for the task (auto-generated by Firebase).
  title: string; // Title of the task.
  description: string; // Description or details of the task.
  dueDate: Date; // Due date and time for the task.
  createdAt: Date; // Timestamp when the task was created.
  completed: boolean; // Indicates whether the task is completed or not.
  
  // createdBy: string; // User ID of the task creator. // TODO implement after authentication flow done
  // TODO: add lastUpdated;
}
